version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5732:5432' # expose pg on port 5732 to not collide with pg from elswhere
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
